#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.


# we may have to add the project to the python import path
# from sys import path

# SITE_ROOT = dirname(dirname(abspath(__file__)))
# path.append(SITE_ROOT)

