#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080
PROJECT_NAME=`cat $OPENSHIFT_REPO_DIR/.project_name`
cd $OPENSHIFT_REPO_DIR/$PROJECT_NAME
$OPENSHIFT_DATA_DIR/bin/uwsgi -s $OPENSHIFT_INTERNAL_IP:$OPENSHIFT_INTERNAL_PORT --socket-protocol http --module $PROJECT_NAME.wsgi:application --pp $OPENSHIFT_REPO_DIR/$PROJECT_NAME -d $OPENSHIFT_DIY_LOG_DIR/app.log --pidfile $OPENSHIFT_TMP_DIR/uwsgi.pid
